config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :planes
  resources :reservations
  resources :flights

  # Seats API route for JS/React to capture
  get "/flights/:id/seats" => "flights#seats", :as => "seats"
  post "/flights/:id/seats" => "flights#set_seat_data", :as => "set_seat"

  # Flight API route for JS/React to capture
  get "/flights/:to/:from/:date" => "flights#get_reserves", :as => "reserves"

  # Origin API route for JS/React to capture
  get "/flights/origin/destination" => "flights#get_origins_destinations", :as => "od"

  get "/flights/:id/staticseats" => "flights#static_seats", :as => "static"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :reservations
  belongs_to :plane, :optional => true
  has_many :seats
   
   def get_seats
      self.seats
   end
=begin
   'get_seats' returns the seat_data array which contains
   a row hash which defines whether or not the seat is reserved
   and who has reserved it. See flights_controller for more information 
   on how this method is utilized.
=end
   def new_seats
      #self.seats.destroy_all
      seats = Seat.create_seats 20
      self.seats << seats
      #self.seats_created = true
      puts "Populated seating array with seat data."
      puts "Created #{seats.length} dummy seats."
      self.save()
      self.seats
   end

   def static_seats 
      unless self.seats_created
         seats = new_seats
      else
         seats = get_seats
      end
   end
end

app/models/plane.rb
class Plane < ApplicationRecord
   has_many :flights

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :flight, :optional => true
end

app/models/seat.rb
class Seat < ApplicationRecord
    belongs_to :plane, optional: true

    def self.create_seats(rows)
        seats = []
        rows.to_i.times do 
            is_reserved = [true, false].sample
            reservee = 'Empty'
            if is_reserved
                reservee = [User.first.name, User.second.name].sample
            end
            seats << create!(
                is_reserved: is_reserved,
                reservee: reservee
            )
        end
        return seats
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
#   def new
#   end
#
#   def create
#   end
#
#   def index
#     respond_to do |format|
# <<<<<<< HEAD
#       format.html { @flights = Flight.all }
#       format.json { render :json Flight.all }
# =======
#       format.html
#       format.json { render :json => Flight.all }
# >>>>>>> 35687df57cf50cad1e14f73ef705038736f96d20
#     end
#   end
#
#   def show
#   end
#
#   def edit
#   end
#
#   def update
#   end
#
#   def destroy
#   end
# end

skip_before_action :verify_authenticity_token, raise: false

# CREATE ###########################
  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.create flight_params
    redirect_to flights_path
  end

  # READ #############################
  def index
    @flights = Flight.all
  end

  def get_reserves
    date = params[:date].split("-").join("/")
    flights = Flight.where origin: params[:to], destination: params[:from], date: date
    puts "ORIGIN: #{params[:from]} DESTINATION: #{params[:to]}"
    if flights.present?
      render :json => {
        flight_data: flights,
        no_result: false
      }
    else
      render :json => {
        no_result: true,
        fail_text: "No flight results"
      }
    end
  end

  def get_origins_destinations
    origin_array = []
    destination_array = []

    Flight.all.each do |fl|
      origin_array << fl.origin
      destination_array << fl.destination
    end

      render :json => {
        origins: origin_array.uniq,
        destinations: destination_array.uniq
      }
  end
    def set_seat_data
    flight = Flight.find params[:id]
    seat_data = params[:seat]
    puts "SEATSSSS: #{flight.seats}"
    puts "INDEX: #{params[:index]}"
    flight.seats[params[:index]].update reservee: seat_data["reservee"], is_reserved: seat_data["is_reserved"]
    flight.save
    render :json => {
        seat_data: flight.seats 
    }
  end

=begin
    This method renders JSON plane data to be captured
    by the front-end. React will loop over every seat object
    and style the grid item based on the "plane.get_seats" method
    call which returns a hash of seat info like: is_reserved and reservee
=end
  def seats
    flight = Flight.find params[:id]
    render :json => {
      :flight_data => {
        rows: flight.plane.rows,
        columns: flight.plane.columns,
        seat_data: flight.seats 
      }
    }
  end

  def static_seats
    flight = Flight.find params[:id]
    render json: {
      seat_data: flight.seats
    }
  end

  def show
    @flight = Flight.find params[:id]
  end

# UPDATE #############################
  def edit
    @flight = Flight.find params[:id]
  end

  def update
    flight = Flight.find params[:id]

    flight.update flight_params

    redirect_to flight_path
  end

# DESTROY #############################
  def destroy
    flight = Flight.find params[:id]
    flight.destroy
    redirect_to flights_path
  end

  private

  def flight_params
    params.require( :flight ).permit( :flight_number, :origin, :destination, :date )
  end

end # FlightsController

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false

  # CREATE ############################################
  def new
    @plane = Plane.new
  end

  def create
    @plane = Plane.new plane_params
    @plane.save
    redirect_to planes_path
  end

  # READ ###########################################
  def index
    @planes = Plane.all
  end

  def show
    @plane = Plane.find params[:id] #instance variable
  end


# UPDATE ####################################
  def edit
    @plane = Plane.find params[:id]
  end

  def update
    plane = Plane.find params[:id]

    plane.update plane_params

    redirect_to plane_path
  end

  def destroy
    plane = Plane.find params[:id]
    plane.destroy
    redirect_to planes_path
  end

  private

  def plane_params
    params.require( :plane ).permit( :name, :rows, :columns  )
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # CREATE ############################################
  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new reservation_params
    @reservation.save
    redirect_to reservations_path
  end

  # READ ###########################################
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find params[:id] #instance variable
  end

# UPDATE ####################################
  def edit
    @reservation = Reservation.find params[:id]
  end

  def update
    reservation = Reservation.find params[:id]

    reservation.update reservation_params

    redirect_to reservation_path
  end

  def destroy
    reservation = Reservation.find params[:id]
    reservation.destroy
    redirect_to reservations_path
  end

  private

  def reservation_params
    params.require( :reservation ).permit( :origin, :destination, :date  )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# CREATE ###########################
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    redirect_to users_path
  end

  # READ #############################
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

# UPDATE #############################
  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]

    user.update user_params

    redirect_to user_path
  end

# DESTROY #############################
  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require( :user ).permit( :name, :admin )
  end

end # UsersController

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flights/_form.html.erb
<%= form_for @flight, html: {multipart: true} do |f| %>

<%= f.label :flight_number, 'Flight Number:' %>
<%= f.number_field :flight_number, required: true %>
<br>

<%= f.label :origin, 'Origin:' %>
<%= f.text_field :origin, required: true %>
<br>

<%= f.label :destination, 'Destination:' %>
<%= f.text_field :destination, required: true %>
<br>

<%= f.label :date, 'Date:' %>
<%= f.text_field :date, required: true %>
<br>

<%= f.submit class:'submit_button' %>

<% end %>

app/views/flights/edit.html.erb
<h2>
  Edit <%= @flight.flight_number %>
</h2>

<%= render partial: 'form' %>
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h2>All Planes</h2>
<%= link_to "Create a new flight", new_flight_path %>
<hr>
  <% @flights.each do |flight| %>
  <li>
    <%= link_to flight.flight_number, flight_path(flight.id) %>
  </li>
  <% end %>

app/views/flights/new.html.erb
<h2>Add a new flight</h2>

<%= render partial: 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<h2> <%= @flight.flight_number %> </h2>

<p>
  <strong>Flight Number:</strong> <%= @flight.flight_number %>
</p>

<p>
  <strong>Origin:</strong> <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong> <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong> <%= @flight.date %>
</p>

<p><%= link_to 'Edit', edit_flight_path(@flight) %></p>
<p><%= link_to 'Delete', flight_path(@flight.id), method: 'delete' %></p>
<p><%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaRailsBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Planes', planes_path %></li>
        <li><%= link_to 'Flights', flights_path %></li>
        <li><%= link_to 'Reservations', reservations_path %></li>
      </ul>
    </nav>


    <%= yield %>
  </body>
</html>

app/views/planes/_form.html.erb
<%= form_for @plane, html: {multipart: true} do |f| %>

<%= f.label :name, 'Name:' %>
<%= f.text_field :name, required: true %>
<br>
<%= f.label :rows, 'Number of Rows:' %>
<%= f.number_field :rows, required: true %>
<br>
<%= f.label :name, 'Number of Columns:' %>
<%= f.number_field :columns, required: true %>
<br>
<%= f.submit class:'submit_button' %>

<% end %>

app/views/planes/edit.html.erb
<h2>
  Edit <%= @plane.name %>
</h2>

<%= render partial: 'form' %>
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<h2>All Planes</h2>
<%= link_to "Create a new plane", new_plane_path %>
<hr>
  <% @planes.each do |plane| %>
  <li>
    <%= link_to plane.name, plane_path(plane.id) %>
  </li>
  <% end %>

app/views/planes/new.html.erb
<h2>Add a new plane</h2>

<%= render partial: 'form' %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<h2> <%= @plane.name %> </h2>

<p>
  <strong>Name:</strong> <%= @plane.name %>
</p>

<p>
  <strong>Rows:</strong> <%= @plane.rows %>
</p>

<p>
  <strong>Columns:</strong> <%= @plane.columns %>
</p>

<p><%= link_to 'Edit', edit_plane_path(@plane) %></p>
<p><%= link_to 'Delete', plane_path(@plane.id), method: 'delete' %></p>
<p><%= link_to 'Back', planes_path %>

app/views/reservations/_form.html.erb
<%= form_for @reservation, html: {multipart: true} do |f| %>

<%= f.label :date, 'Flight Date:' %>
<%= f.text_field :date, required: true %>
<br>

<%= f.label :origin, 'Origin:' %>
<%= f.text_field :origin, required: true %>
<br>

<%= f.label :destination, 'Destination:' %>
<%= f.text_field :destination, required: true %>
<br>

<%= f.submit class:'submit_button' %>

<% end %>

app/views/reservations/edit.html.erb
<h2>
  Edit <%= @reservation.name %>
</h2>

<%= render partial: 'form' %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h2>All Reservations</h2>
<%= link_to "Make a new reservation", new_reservation_path %>
<hr>
  <% @reservations.each do |reservation| %>
  <li>
    <%= link_to reservation.date, reservation_path(reservation.id) %>
  </li>
  <% end %>

app/views/reservations/new.html.erb
<h2>Make a new reservation</h2>

<%= render partial: 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<h2> <%= @reservation.date %> </h2>

<p>
  <strong>Flight Date:</strong> <%= @reservation.date %>
</p>

<p>
  <strong>Origin:</strong> <%= @reservation.origin %>
</p>

<p>
  <strong>Destination:</strong> <%= @reservation.destination %>
</p>



<p><%= link_to 'Edit', edit_reservation_path(@reservation) %></p>
<p><%= link_to 'Delete', reservation_path(@reservation.id), method: 'delete' %></p>
<p><%= link_to 'Back', reservations_path %>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>

<%= f.label :name, 'Name:' %>
<%= f.text_field :name, required: true %>
<br>
<br>
<%= f.submit class:'submit_button' %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>All Users</h2>
<%= link_to "Create a new user", new_user_path %>
<hr>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user.id) %>
      <%= user.admin %>
    </li>
  <% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: 'form' %>

<br>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2> <%= @user.name %> </h2>

<p>
  <strong>Name:</strong> <%= @user.name %>
</p>
<p><%= link_to 'Edit', edit_user_path(@user) %></p>
<p><%= link_to 'Delete', user_path(@user.id), method: 'delete' %></p>
<p><%= link_to 'Back', users_path %></p>